public enum EffectType
{
    None = 0,
    Grenade = 1,
    Heal = 2,
    RageTeeth = 3,
    StunStars = 4,
    StunStarsEnd = 5,
    LifestealPuh = 6,
    LifestealCircle = 7,
    LifestealSkulls = 8,
    Regeneration = 9,
    ShockWave = 10,
    InstantReload = 11,
    RageLv2 = 12,
    RageLv3 = 13,
    RageLv4 = 14,
    Sprint = 15,
    ImmortalyDefend = 16,
    ImmortalyIdle = 17,
    DiveAim = 18,
    DiveExplosion = 19,
    Reload = 20,
    Dash = 21,
}